apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blackbox-exporter.fullname" . }}-config
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ .Values.blackboxExporter.config | indent 4 }}

